# Generated by Django 4.1.3 on 2022-11-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.SmallIntegerField(blank=True, verbose_name='Страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
    ]
